### ISSUE TITLE
Also remove more

### ISSUE THREAD

**Issue by ghost** [Fiz-Victor/random-addon#2]
UDPFlood, and all the netproxy commands, and the webhook commands.

**Comment by ghost** [comment]
UDPFlood, LeftHanded, MassPayout, ServerOpNuke, XsDupe, armorStandCrash, NullExceptionCrash, SwingCrash, WorldBorderCrash, BoatFling. 
SpoofNameCommand, SpoofServerBrandCommand, SubnetCalculatorCommand, WebhookSendCommand, WebhookDeleteCommand., SpoofUUIDCommand, NetProxyCommand, NetProxyDisconnectCommand, IPLookupCommand, IPBlacklistCommand, and NSLookupCommand.


This is everything that needs to be removed.

**Comment by hexadecimal233** [comment]
should be removed

**Comment by ghost** [comment]
Thanks.
