### ISSUE TITLE
You had 2 fucking chances.

### ISSUE THREAD

**Issue by ghost** [Fiz-Victor/random-addon#3]
Remove my fucking code or ill be taking legal action. Don't be a retard and move it to a different package.

Remove:

BuildRandom, UDPFlood, and ChunkCrash.

**Comment by ghost** [comment]
Literally all you did for UDPFlood is remove:

  }

        if (allPacketsSent) {
            info(" - UDP- ");
            info("Server IP: " + serverIp);
            info("Server Port: " + serverPort);
            info("Total data sent: " + formatData(totalDataSent));
            toggle();
        }
    }


    private boolean isValidIpAddress(String ipAddress) {
        String[] parts = ipAddress.split("\\.");
        if (parts.length != 4) {
            return false;
        }

        for (String part : parts) {
            try {
                int num = Integer.parseInt(part);
                if (num < 0 || num > 255) {
                    return false;
                }
            } catch (NumberFormatException e) {
                return false;
            }
        }
        return true;
    }


    @EventHandler
    private void onGameLeft(GameLeftEvent event) {
        if (autoDisable.get()) {
            toggle();
        }
    }

    private String formatData(long bytes) {
        double kilobytes = bytes / 1000.0;
        double megabytes = kilobytes / 1000.0;
        double gigabytes = megabytes / 1000.0;

        if (gigabytes >= 1.0) {
            return String.format("%.2f GB", gigabytes);
        } else if (megabytes >= 1.0) {
            return String.format("%.2f MB", megabytes);
        } else if (kilobytes >= 1.0) {
            return String.format("%.2f KB", kilobytes);
        } else {
            return bytes + " bytes";
        }
    }

}

If the class isn't gone, or you renamed it i am taking legal action.

**Comment by hexadecimal233** [comment]
removed udp flood
